---
- name: Hello World – Ansible Automation Platform demo
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    app_name: "Ansible Automation Platform"
    environment: "lab"

  tasks:
    - name: Display welcome message
      ansible.builtin.debug:
        msg:
          - "Welcome to {{ app_name }}"
          - "Environment: {{ environment }}"
          - "Playbook executed successfully via AAP"

